version: '3.8'

services:
  spring:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.spring
    image: spring
    container_name: spring
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ${HLS_PATH}/hls:/tmp/hls
      - ${HLS_PATH}/hls_audio:/tmp/hls_audio
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  nginx-rtmp:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.nginx
    image: nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:8081"
    volumes:
      - ${HLS_PATH}/hls:/tmp/hls
      - ${HLS_PATH}/hls_audio:/tmp/hls_audio
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
