services:
  kumoh-talk-streaming-spring:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.spring
      network: host
    image: kumoh-talk-streaming-spring
    container_name: kumoh-talk-streaming-spring
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ${HLS_PATH}/hls:/tmp/hls
      - ${HLS_PATH}/hls_audio:/tmp/hls_audio
      - ${HOST_CLOUDFRONT_PRIVATE_KEY_PATH}:${CLOUDFRONT_PRIVATE_KEY_PATH}
    depends_on:
      kumoh-talk-streaming-mysql:
        condition: service_healthy
      kumoh-talk-streaming-redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - kumoh-talk-streaming-network

  kumoh-talk-streaming-nginx-rtmp:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.nginx
    image: kumoh-talk-streaming-nginx-rtmp
    container_name: kumoh-talk-streaming-nginx-rtmp
    ports:
      - "1935:1935"
      - "9091:8081"
    volumes:
      - ${HLS_PATH}/hls:/tmp/hls
      - ${HLS_PATH}/hls_audio:/tmp/hls_audio
    depends_on:
      kumoh-talk-streaming-spring:
        condition: service_healthy
    networks:
      - kumoh-talk-streaming-network

  kumoh-talk-streaming-mysql:
    image: mysql:8.0
    container_name: kumoh-talk-streaming-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kumoh-talk-streaming-network

  kumoh-talk-streaming-redis:
    image: redis:7.2
    container_name: kumoh-talk-streaming-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - kumoh-talk-streaming-network

volumes:
  mysql_data:
  redis_data:

networks:
  kumoh-talk-streaming-network:
